import puppeteer from 'puppeteer';
const SUPA_URL = 'https://ydcbxqrnmnbceyzqgbui.supabase.co';
const ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkY2J4cXJubW5iY2V5enFnYnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3Mzg0NjYsImV4cCI6MjA4OTMxNDQ2Nn0.y-lauFU8c9eTP0RJL_zveEF4JE96KiTvJ46FrvYZmfY';
const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
await page.setViewport({ width: 390, height: 844, isMobile: true });
await page.goto('http://localhost:3462/login', { waitUntil: 'networkidle2' });
await page.type('input[type="email"]', 'dmitrykokrok@gmail.com');
await page.type('input[type="password"]', 'dmitrykokrok');
const btn = await page.$('button[type="submit"]');
if (btn) await btn.click();
await new Promise(r => setTimeout(r, 4000));
await page.screenshot({ path: 'C:\\Users\\Dimax\\.openclaw\\media\\test-header.png', clip: { x: 0, y: 0, width: 390, height: 60 } });
await page.screenshot({ path: 'C:\\Users\\Dimax\\.openclaw\\media\\test-game2.png' });
await page.goto('http://localhost:3462/game', { waitUntil: 'networkidle2' });
await new Promise(r => setTimeout(r, 2000));
await page.screenshot({ path: 'C:\\Users\\Dimax\\.openclaw\\media\\test-game3.png' });
console.log('Done');
await browser.close();
